---
title: "Pollinators_Agro_report"
author: "André F. Henriques"
format:
  html:
    theme: flatly
    grid:
      margin-width: 100px
    toc: true
    toc-float: true
    toc-location: left
    toc-depth: 4
    number-sections: true
    number-depth: 4
    code-overflow: wrap
    self-contained: true
engine: knitr
execute:
  eval: false
include-in-header:
  - text: |
      <style>
      .cell-output-stdout code {
        word-break: break-word   !important;
        white-space: pre-wrap !important;
      }
      </style>
---

# File Management

## Correcting Formatting Mistakes

Some original `fastq` files came from CDGenomics with a formatting error where the length of the quality score lines was longer than the DNA sequence lines.
This was corrected using `fastqTipCutter.py`.
The script was wrapped for each sequencing batch using `fastqTipCuterWrapper.sh`.

Results in `mnt/data2/Project_Polli_agro/Operational/0_pre_analysis_rawdata_formating`.

## Merging and Renaming Files

Files from different sequencing batches that belonged to the same sample were merged.

First, "_1st" and "_2nd" was appended to the names of the files from the first and second batches, respectively.
Then, merging was performed using script `fastqMerger_v2.sh`.

Fastq files were then renamed using script `fastqRenamer.sh`, using the following key: `/mnt/data2/Project_Polli_agro/Operational/2_sample_lists/plate_CDGenomics_key.txt`.
**These are the original working names, set at the time of sampling**.

Results are in `/mnt/data2/Project_Polli_agro/Operational/0_pre_analysis_rawdata_formating/2_merge_and_rename`.

## Subsetting SSF Samples

Some samples collected for the other projects were adopted into this one. 
To make sample names consistent, some `fastq` files were renamed again using `fastqRenamer.sh`, using the following key: `/mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/names_changed_2run.txt`

Results are in `/mnt/data2/Project_Polli_agro/Operational/0_pre_analysis_rawdata_formating/2_merge_and_rename`.

Then, only samples to be used in this project were selected and moved to the `raw_data` directory.
The **197** sample names can be found `/mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/SSF_sample_list_2nd_run.txt`.
This was done using `copy_files.sh`

# Raw Data Filtering

Raw data `fastq` files were analyzed with `fastqc` and the results were summarized using `multiqc`: [summarized `fastqc` results](html_reports/1_rawdata_fastqc_multiqc_report.html).

## `fastp`

`fastq` files were filtered with `fastp v0.23.4`.

```{bash}
bash /mnt/data2/Project_Polli_agro/Operational/5_scripts/2_filtering/fastpRun.sh \
-i /mnt/data2/Project_Polli_agro/Operational/1_raw_data/ \
-o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/00_qc/00_fastp/ \
-s /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/SSF_sample_list_2nd_run.txt \
-x '--detect_adapter_for_pe --adapter_fasta /mnt/data2/Project_Polli_agro/Operational/2_metadata/00_CDGenomics/CDGenomics_adapters_list.fa --dedup --dup_calc_accuracy 6 --trim_poly_g --trim_poly_x --max_len1 140 --max_len2 140 --length_required 140 --overrepresentation_analysis --qualified_quality_phred 20 --thread 16'
```

`fastp` reports were summarized using `multiqc`: [sumarized `fastp` results](html_reports/2_fastp_summarized_results_multiqc_report.html).

Post-filtering `fastq` files were analyzed with `fastqc` and the results were summarized using `multiqc`: [summarized `fastqc` results](html_reports/3_post_filtering_fastq_multiqc_report.html).

`fastp` files were ran one second time, after filtering, to see the duplication rates.

```{bash}
bash /mnt/data2/Project_Polli_agro/Operational/5_scripts/2_filtering/fastpRun.sh \
-i /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/00_qc/00_fastp/ \
-o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/00_qc/00_fastp/03_post_fastp_duplication/ \
-s /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/SSF_sample_list_2nd_run.txt \
-x '--dup_calc_accuracy 6 -A -G -Q -L --thread 50'
```

`fastp` duplication rates reports were summarized using `multiqc`: [sumarized `fastp` results](html_reports/4_fastP_duplication_rate_post_filtering.html).


# SNP calling

SNP calling was done with `Stacks` v.2.65

## `process_radtags`

`process_radtags` was run on already demultiplexed and filtered `fastq` files.
Input file names were changed from "_R1." and "_R2." to "\_R1\_." and "\_R2\_.", otherwise Stacks wouldn't detect them.

```{bash}
process_radtags \
--paired \
--in-path /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/00_qc/00_fastp/ \
-o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/01_process_radtags \
--threads 32 --clean --rescue -e pstI
```

## `BWA` Mapping

Reference genomes were indexed with `bwa-mem2 index`. (*note: chromosome names were shortened*)

```{bash}
bwa-mem2 index -p a_flavipes_ref_genome a_flavipes_ref_genome.fa 
bwa-mem2 index -p b_terrestris_ref_genome b_terrestris_ref_genome.fa 
bwa-mem2 index -p l_malachurum_ref_genome l_malachurum_ref_genome.fa 
```

Mapping for each species was performed with `BWA` and `Samtools` wrapped under `bwaSamtoolsWrapper.sh`. 

```{bash}
bash /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/2_SNP_calling/bwaSamtoolsWrapper.sh -i /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/01_process_radtags/ -s /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/AND_sample_list_stacks_2nd_run.txt -o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/02_BWA/AND/ -n /mnt/data2/Project_Polli_agro/Operational/6_reference_genomes/a_flavipes/a_flavipes_ref_genome -x '-t 10'

bash /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/2_SNP_calling/bwaSamtoolsWrapper.sh -i /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/01_process_radtags/ -s /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/BOM_sample_list_stacks_2nd_run.txt -o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/02_BWA/BOM/ -n /mnt/data2/Project_Polli_agro/Operational/6_reference_genomes/b_terrestris/b_terrestris_ref_genome -x '-t 10'

bash /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/2_SNP_calling/bwaSamtoolsWrapper.sh -i /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/01_process_radtags/ -s /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/LML_sample_list_stacks_2nd_run.txt -o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/02_BWA/LML/ -n /mnt/data2/Project_Polli_agro/Operational/6_reference_genomes/l_malachurum/l_malachurum_ref_genome -x '-t 10'
```

`BWA` reports were summarized using `multiqc`: [sumarized `BWA` results](html_reports/5_post_BWA_multiqc.html).

## `ref_map.pl`

BAM files had to be changed from "_sorted_filtered.bam" to ".bam" because `stacks` wouldn't read them otherwise.

`ref_map.pl` was run for each species.

```{bash}
ref_map.pl \
--samples /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/02_BWA/AND/ \
--popmap /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/Popmap_AND.txt \
-o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/03_refmap/AND/ \
-X "populations: -R 0.8 --vcf --ordered-export --fasta-loci --fasta-samples --genepop --structure --radpainter --plink --phylip -t 80" -X "gstacks: -t 80"

ref_map.pl \
--samples /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/02_BWA/BOM/ \
--popmap /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/Popmap_BOM.txt \
-o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/03_refmap/BOM/ \
-X "populations: -R 0.8 --vcf --ordered-export --fasta-loci --fasta-samples --genepop --structure --radpainter --plink --phylip -t 80" -X "gstacks: -t 80"

ref_map.pl \
--samples /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/02_BWA/LML/ \
--popmap /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/Popmap_LML.txt \
-o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/03_refmap/LML/ \
-X "populations: -R 0.8 --vcf --ordered-export --fasta-loci --fasta-samples --genepop --structure --radpainter --plink --phylip -t 80" -X "gstacks: -t 80"

```

`ref_map.pl` reports were summarized using `multiqc`: [sumarized `ref_map.pl` results](html_reports/6_ref_map_multiqc_report_.html).

## `BCFTools`

VCF files were filtered with `BCFTools`. Filtering parameters were as follow: only bi-allelic SNPs, with minor allele count of equal or above 2, mean depth between 10 and 100 and a missing frequency bellow 20%.

VCF filtered files were thinned with a window of 1000bp, keeping only the first SNP in each window. 

```{bash}
bash /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/2_SNP_calling/filterVCF.sh /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/03_refmap/AND/populations.snps.vcf /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/AND_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20.vcf.gz /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/AND_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp.vcf.gz

bash /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/2_SNP_calling/filterVCF.sh /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/03_refmap/BOM/populations.snps.vcf /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/BOM_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20.vcf.gz /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/BOM_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp.vcf.gz

bash /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/2_SNP_calling/filterVCF.sh /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/03_refmap/LML/populations.snps.vcf /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/LGL_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20.vcf.gz /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/LGL_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp.vcf.gz
```

## `VCFTools` - Kindship analysis

`VCFTools` was used to calculate and output a relatedness statistic. The relatedness value to use is 0.20. From a par of individuals with a relatedness value higher than 0.20, remove the one with the lowest coverage/quality.

```{bash}
vcftools --gzvcf ./AND_stk_mac2_bi_meanDP10-100_maxmiss20_centersnp.vcf.gz --out AND_relatedness2 --relatedness2

vcftools --gzvcf ./BOM_stk_mac2_bi_meanDP10-100_maxmiss20_centersnp.vcf.gz --out BOM_relatedness2 --relatedness2

vcftools --gzvcf ./LGL_stk_mac2_bi_meanDP10-100_maxmiss20_centersnp.vcf.gz --out LGL_relatedness2 --relatedness2
```

Remove individuals that are related/from the same colony

```{bash}
bcftools view --samples ^BOM_SAH_002_poll504,BOM_ARRA_001_poll026 -Oz -o BOM_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp_rm.vcf.gz BOM_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp.vcf.gz

bcftools view --samples ^BOM_SAH_002_poll504,BOM_ARRA_001_poll026 -Oz -o BOM_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_rm.vcf.gz BOM_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20.vcf.gz
```

# Structure analysis

## `fineRADstructure`

```{bash}
Rscript /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/3_structure/fineRADStructureWrapper.R /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/AND_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20.vcf.gz  /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/02_structure/01_fineRADstructure/AND/ /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/3_structure/FinestructureLibrary.R 

Rscript /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/3_structure/fineRADStructureWrapper.R /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/BOM_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_rm.vcf.gz    /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/02_structure/01_fineRADstructure/BOM/ /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/3_structure/FinestructureLibrary.R 

Rscript /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/3_structure/fineRADStructureWrapper.R /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/LGL_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20.vcf.gz  /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/02_structure/01_fineRADstructure/LGL/ /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/3_structure/FinestructureLibrary.R 
```

## `Structure Threader`

```{bash}
structure_threader run -i /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/AND_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp.vcf -o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/02_structure/02_structure_threader/AND/ --ind /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/AND_structure_popfile.txt -als ~/miniconda3/envs/ST/bin/alstructure_wrapper.R -K 5 -t 100

structure_threader run -i /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/BOM_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp_rm.vcf -o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/02_structure/02_structure_threader/BOM/ --ind /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/BOM_structure_popfile.txt -als ~/miniconda3/envs/ST/bin/alstructure_wrapper.R -K 5 -t 100

structure_threader run -i /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/LGL_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp.vcf -o /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/02_structure/02_structure_threader/LGL/ --ind /mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/LGL_structure_popfile.txt -als ~/miniconda3/envs/ST/bin/alstructure_wrapper.R -K 5 -t 100
```

## `PCA`

```{bash}
Rscript /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/3_structure/snp_pca_static.R 
/mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/AND_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp.vcf
/mnt/data2/Project_Polli_agro/Operational/4_data_analysis/02_structure/03_PCA/AND/AND_snp_PCA
/mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/AND_structure_popfile.txt

Rscript /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/3_structure/snp_pca_static.R 
/mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/BOM_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp_rm.vcf /mnt/data2/Project_Polli_agro/Operational/4_data_analysis/02_structure/03_PCA/BOM/BOM_snp_PCA
/mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/BOM_structure_popfile.txt

Rscript /mnt/data2/Project_Polli_agro/Operational/5_scripts/Pollinators_Agro_Scripts/3_structure/snp_pca_static.R 
/mnt/data2/Project_Polli_agro/Operational/4_data_analysis/01_snpcall/04_BCFtools/LGL_stk_minDP5_minGQ30_bi_mac2_meanDP10-100_maxmiss20_thinned1kbp.vcf
/mnt/data2/Project_Polli_agro/Operational/4_data_analysis/02_structure/03_PCA/LGL/LGL_snp_PCA
/mnt/data2/Project_Polli_agro/Operational/2_metadata/02_SSF_samples/01_sample_files/LGL_structure_popfile.txt
```

# Land-use analysis

Land-use analyses were done using the following R packages: landscapemetrics_2.1.3, terra_1.8-5, sf_1.0-16. 

The analyses can be accessed at [land-use analyses](html_reports/landuse/EnvironmentalLandUseData.html).